//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.RfqServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RfqServiceReference.CmsWebServiceSoap")]
    public interface CmsWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRfq", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateRfq(System.Data.DataTable RfqDt, System.Data.DataTable RoutesDt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRfq", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreateRfqAsync(System.Data.DataTable RfqDt, System.Data.DataTable RoutesDt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/testcon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string testcon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/testcon", ReplyAction="*")]
        System.Threading.Tasks.Task<string> testconAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CmsWebServiceSoapChannel : Portal.RfqServiceReference.CmsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CmsWebServiceSoapClient : System.ServiceModel.ClientBase<Portal.RfqServiceReference.CmsWebServiceSoap>, Portal.RfqServiceReference.CmsWebServiceSoap {
        
        public CmsWebServiceSoapClient() {
        }
        
        public CmsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CmsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CmsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CmsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateRfq(System.Data.DataTable RfqDt, System.Data.DataTable RoutesDt) {
            return base.Channel.CreateRfq(RfqDt, RoutesDt);
        }
        
        public System.Threading.Tasks.Task<string> CreateRfqAsync(System.Data.DataTable RfqDt, System.Data.DataTable RoutesDt) {
            return base.Channel.CreateRfqAsync(RfqDt, RoutesDt);
        }
        
        public string testcon() {
            return base.Channel.testcon();
        }
        
        public System.Threading.Tasks.Task<string> testconAsync() {
            return base.Channel.testconAsync();
        }
    }
}
